---
name: Linting

"on":
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_YAML_YAMLLINT: true
          VALIDATE_ANSIBLE_ANSIBLE_LINT: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
